spring:
  application:
    name: dukaan
  datasource:
    url: jdbc:postgresql://localhost:5432/tripplings?currentSchema=dukaan
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create